version: "3"

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  sonarqube:
    container_name: sonarqube
    image: "sonarqube:8.9.7-community"
    ports:
      - "9000:9000"
    volumes:
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_extensions:/opt/sonarqube/extensions
     - sonarqube_logs:/opt/sonarqube/logs
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
 

volumes:
  db:
  nexus-data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_data:
  grafana-data:
  




